---
apiVersion: v1
kind: Secret
metadata:
  name: Detection-service-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/OpenShiftCommons/Detection-service-gitops